# Generated by Django 2.1.4 on 2018-12-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_goodsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
            ],
        ),
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_number',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_price',
            field=models.FloatField(verbose_name='价格'),
        ),
    ]
